server:
  port: 1988
  servlet:
    context-path: /xrateservice2

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

---

# Local profile
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password$123
    url: jdbc:mysql://localhost:3306/xrate?serverTimezone=UTC
    username: root

service:
  access_key: 743ca3b5fa46942d9a63296a6e1ea426
  url:
    latest: api.exchangeratesapi.io/v1/latest
    historical: api.exchangeratesapi.io/v1/
    convert: api.exchangeratesapi.io/v1/convert

# 120000 2 minute
update_rates:
  cron: 120000

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
  instances:
    service2:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
      ignoreExceptions:
          - com.gl.orderManagementApp.service.MyException

resilience4j.ratelimiter:
  instances:
    service2:
      limitForPeriod: 10
      limitRefreshPeriod: 100000
      timeoutDuration: 1000ms


resilience4j.retry:
  instances:
    retryService2:
      maxRetryAttempts: 5
      waitDuration: 10000

resilience4j.bulkhead:
  instances:
    bulkheadService2:
      maxWaitDuration: 10ms
      maxConcurrentCall: 30

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadService2:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1